from fpdf import FPDF

class PDF(FPDF):
    def header(self):
        pass
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, 'lablab.ai Agentic Commerce on Arc Hackathon | January 2026', 0, 0, 'C')

pdf = PDF('L', 'mm', 'A4')  # Landscape
pdf.set_auto_page_break(auto=True, margin=15)

# Slide 1: Title
pdf.add_page()
pdf.set_fill_color(26, 10, 46)
pdf.rect(0, 0, 297, 210, 'F')
pdf.set_font('Arial', 'B', 48)
pdf.set_text_color(167, 139, 250)
pdf.set_xy(20, 40)
pdf.cell(0, 20, 'Agentic Commerce on Arc', 0, 1)
pdf.set_font('Arial', '', 24)
pdf.set_text_color(200, 200, 200)
pdf.set_xy(20, 70)
pdf.cell(0, 10, 'AI Agents That Shop, Create, and Trade for You', 0, 1)
pdf.set_font('Arial', 'I', 16)
pdf.set_text_color(196, 181, 253)
pdf.set_xy(20, 100)
pdf.multi_cell(250, 8, '"In a world where AI makes labor and intelligence abundant, creativity and proving you had the idea first become the true differentiators."')

# Slide 2: Vision
pdf.add_page()
pdf.set_fill_color(26, 10, 46)
pdf.rect(0, 0, 297, 210, 'F')
pdf.set_font('Arial', 'B', 36)
pdf.set_text_color(167, 139, 250)
pdf.set_xy(20, 20)
pdf.cell(0, 15, 'The Vision', 0, 1)
pdf.set_font('Arial', '', 14)
pdf.set_text_color(255, 255, 255)
features = [
    "Natural Language Product Creation - Describe your dream product in plain English",
    "AI-Generated Images - FLUX creates photorealistic product images instantly",
    "Escrow Transaction Proof - Verify configured Arc escrow payments",
    "Stablecoin Payments - Circle USDC integration for seamless commerce"
]
y = 50
for f in features:
    pdf.set_xy(25, y)
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(5, 8, chr(149), 0, 0)  # bullet
    pdf.set_font('Arial', '', 14)
    pdf.cell(0, 8, ' ' + f, 0, 1)
    y += 20

# Slide 3: Vibe Coded
pdf.add_page()
pdf.set_fill_color(26, 10, 46)
pdf.rect(0, 0, 297, 210, 'F')
pdf.set_font('Arial', 'B', 36)
pdf.set_text_color(167, 139, 250)
pdf.set_xy(20, 20)
pdf.cell(0, 15, '100% Vibe Coded', 0, 1)
pdf.set_font('Arial', '', 14)
pdf.set_text_color(255, 255, 255)
pdf.set_xy(20, 45)
pdf.cell(0, 8, 'This entire project was built through pure AI collaboration:', 0, 1)
items = [
    "Architecture decisions via natural language dialogue",
    "React/TypeScript components generated by AI agents",
    "Smart contracts deployed through AI assistance",
    "Testing and debugging with AI pair programming",
    "Even this video was programmatically generated with Remotion"
]
y = 60
for item in items:
    pdf.set_xy(25, y)
    pdf.cell(5, 8, chr(149), 0, 0)
    pdf.cell(0, 8, ' ' + item, 0, 1)
    y += 15
pdf.set_font('Arial', 'B', 16)
pdf.set_xy(20, 150)
pdf.cell(0, 10, 'No traditional coding. Just creative direction and AI execution.', 0, 1)

# Slide 4: Tech Stack & Roadmap
pdf.add_page()
pdf.set_fill_color(26, 10, 46)
pdf.rect(0, 0, 297, 210, 'F')
pdf.set_font('Arial', 'B', 36)
pdf.set_text_color(167, 139, 250)
pdf.set_xy(20, 20)
pdf.cell(0, 15, 'Tech Stack & Roadmap', 0, 1)
pdf.set_font('Arial', '', 12)
pdf.set_text_color(255, 255, 255)
pdf.set_xy(20, 45)
tech = "React 18 | TypeScript | Vite | Solidity | Arc Blockchain | FLUX/Replicate | Circle USDC | Remotion | Railway"
pdf.cell(0, 8, tech, 0, 1)
pdf.set_font('Arial', 'B', 18)
pdf.set_text_color(196, 181, 253)
pdf.set_xy(20, 70)
pdf.cell(0, 10, 'The Roadmap:', 0, 1)
pdf.set_font('Arial', '', 14)
pdf.set_text_color(255, 255, 255)
roadmap = [
    "TODAY: AI-generated product images with SimpleEscrow purchases",
    "TOMORROW: AI-generated music tracks with provable timestamps",
    "FUTURE: 3D scans, fashion designs, architectural concepts"
]
y = 90
for r in roadmap:
    pdf.set_xy(25, y)
    pdf.cell(5, 8, chr(149), 0, 0)
    pdf.cell(0, 8, ' ' + r, 0, 1)
    y += 15

# Slide 5: Try It Now
pdf.add_page()
pdf.set_fill_color(26, 10, 46)
pdf.rect(0, 0, 297, 210, 'F')
pdf.set_font('Arial', 'B', 36)
pdf.set_text_color(167, 139, 250)
pdf.set_xy(20, 20)
pdf.cell(0, 15, 'Try It Now', 0, 1)
pdf.set_font('Arial', '', 14)
pdf.set_text_color(200, 200, 200)
pdf.set_xy(20, 50)
pdf.cell(40, 8, 'Live Demo:', 0, 0)
pdf.set_text_color(255, 255, 255)
pdf.cell(0, 8, 'frontend-production-dd6f.up.railway.app', 0, 1)
pdf.set_text_color(200, 200, 200)
pdf.set_xy(20, 65)
pdf.cell(40, 8, 'GitHub:', 0, 0)
pdf.set_text_color(255, 255, 255)
pdf.cell(0, 8, 'github.com/DNYoussef/agentic-commerce-arc', 0, 1)
pdf.set_text_color(200, 200, 200)
pdf.set_xy(20, 80)
pdf.cell(40, 8, 'Contract:', 0, 0)
pdf.set_text_color(255, 255, 255)
pdf.cell(0, 8, '0x1D10c53dCa5931acdc8f6b8F9AA0ed674ae94171', 0, 1)
pdf.set_font('Arial', 'B', 18)
pdf.set_text_color(34, 197, 94)
pdf.set_xy(20, 120)
pdf.multi_cell(250, 10, 'The future belongs to those who imagine and allocate, not those who merely execute.')
pdf.set_font('Arial', 'I', 14)
pdf.set_text_color(148, 163, 184)
pdf.set_xy(20, 160)
pdf.cell(0, 8, 'Built in 48 hours through pure vibe coding.', 0, 1)

pdf.output('D:/Projects/agentic-commerce-arc/submission/presentation.pdf')
print("PDF created successfully!")
